### ISSUE TITLE
how to solve the issue

### ISSUE THREAD

**Issue by ourren** [JamesPHoughton/PySD-Cookbook#14]
Hi , James

When I use 'pysd' library to write some program, it shows this error as below. How can I solve this isssue. Thanks.

```
%pylab inline
import pysd

model = pysd.read_vensim('./A4.mdl')
stocks = model.run()
```

_

> Populating the interactive namespace from numpy and matplotlib
> 
>   File "./A4.py", line 66
>     @cache('step')
>     ^
> SyntaxError: invalid syntax

_

**Comment by JamesPHoughton** [comment]
That is rather interesting. If you'd like to send me the `.py` file, I can have a closer look - there doesn't seem to be a syntax problem in what you've posted here, so its probably something internal to A4.py. If you'd like, you can send it to me at james.p.houghton@gmail.com.

**Comment by ourren** [comment]
Sent~

**Comment by JamesPHoughton** [comment]
Moved to https://github.com/JamesPHoughton/pysd/issues/83
